# config.yaml
defaults:
  period: "30m"
  backup_retention: 5 # Keep last 5 backups per branch
  log_level: "normal" # Options: "verbose" (all branch logs), "normal" (progress updates), "quiet" (errors only)

repositories:
- name: "dotfiles"
  url: "https://github.com/msxdan/dotfiles.git"
  branches: [ "*" ]
  path: "dotfiles"
  auth:
    type: "http"
    username: "msxdan"
    password: $REPOVAULT_GITHUB_TOKEN

- name: "dotfiles_private"
  url: "https://github.com/msxdan/dotfiles_private.git"
  branches: [ "main" ]
  path: "dotfiles_private"
  auth:
    type: "http"
    username: "msxdan"
    password: $REPOVAULT_GITHUB_TOKEN

- name: "homelab-private"
  url: "https://github.com/msxdan/homelab-private.git"
  branches: [ "*" ]
  path: "homelab-private"
  auth:
    type: "http"
    username: "msxdan"
    password: $REPOVAULT_GITHUB_TOKEN

- name: "zet"
  url: "https://github.com/msxdan/zet.git"
  branches: [ "master" ]
  path: "zet"
  auth:
    type: "http"
    username: "msxdan"
    password: $REPOVAULT_GITHUB_TOKEN

- name: "marvincloud.io"
  url: "https://github.com/msxdan/marvincloud.io.git"
  branches: [ "main" ]
  path: "marvincloud.io"
  auth:
    type: "http"
    username: "msxdan"
    password: $REPOVAULT_GITHUB_TOKEN

- name: "mm-ongres"
  url: "git@gitlab.ongres.com:ongresportal/mm-energia/mm-energia.git"
  branches: [ "*" ]
  path: "mm-ongres"
  auth:
    type: "ssh"
    ssh_key_path: "ssh-keys/gitlab_ongres_com_ed25519"
    ssh_key_password: $REPOVAULT_SSH_KEY_PASSWORD

- name: "infrastructure"
  url: "git@github.com:masmovil/infrastructure.git"
  branches: [ "master" ]
  path: "infrastructure"
  auth:
    type: "ssh"
    ssh_key_path: "ssh-keys/github_com_ed25519"
    ssh_key_password: $REPOVAULT_SSH_KEY_PASSWORD

- name: "kubernetes-clusters"
  url: "git@github.com:masmovil/kubernetes-clusters.git"
  branches: [ "master" ]
  auth:
    type: "ssh"
    ssh_key_path: "ssh-keys/github_com_ed25519"
    ssh_key_password: $REPOVAULT_SSH_KEY_PASSWORD

- name: "insurance"
  url: "git@github.com:masmovil/insurance.git"
  branches: [ "master", "frontend-dev" ]
  auth:
    type: "ssh"
    ssh_key_path: "ssh-keys/github_com_ed25519"
    ssh_key_password: $REPOVAULT_SSH_KEY_PASSWORD

- name: "lucera-infra"
  url: "git@github.com:luceraenergia/lucera-infra.git"
  branches: [ "*" ]
  path: "lucera-infra"
  auth:
    type: "ssh"
    ssh_key_path: "ssh-keys/github_com_ed25519"
    ssh_key_password: $REPOVAULT_SSH_KEY_PASSWORD

- name: "masmovil-dns"
  url: "git@github.com:masmovil/masmovil-dns.git"
  branches: [ "master" ]
  auth:
    type: "ssh"
    ssh_key_path: "ssh-keys/github_com_ed25519"
    ssh_key_password: $REPOVAULT_SSH_KEY_PASSWORD
