name: Renovate

on:
  schedule:
    - cron: '0 2 * * 1-5'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'debug'
        type: choice
        options:
          - info
          - debug
          - trace

env:
  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}